modLoader="javafml"
loaderVersion="[4,)"
license="MIT"
logoFile="icon.png"
issueTrackerURL="https://github.com/cinderworks-mc/plinthworks/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="Cinder Works"
description='''plinths you teach to move and filter items, with linking across distance.'''

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="[21.1.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="[1.21.1,1.21.2)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="create"
type="optional"
versionRange="[0,)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="jei"
type="optional"
versionRange="[0,)"
ordering="NONE"
side="CLIENT"

[[dependencies.${mod_id}]]
modId="emi"
type="optional"
versionRange="[0,)"
ordering="NONE"
side="CLIENT"
